# Generated by Django 3.1.6 on 2021-02-04 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='eliminado',
            new_name='disponible',
        ),
    ]
